# Generated by Django 5.0.6 on 2026-06-13 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platforms', '0002_directmessage_usernotification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('url', models.URLField(max_length=500, verbose_name='الرابط')),
                ('link_type', models.CharField(choices=[('website', 'موقع ويب'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'X (Twitter)'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('snapchat', 'Snapchat'), ('app_store', 'App Store'), ('play_store', 'Google Play'), ('support', 'دعم فني'), ('documentation', 'وثائق / مساعدة'), ('payment', 'بوابة دفع'), ('custom', 'رابط مخصص')], default='website', max_length=30, verbose_name='نوع الرابط')),
                ('category', models.CharField(choices=[('social', 'وسائل التواصل'), ('website', 'المواقع'), ('app', 'تطبيقات الجوال'), ('support', 'الدعم والمساعدة'), ('legal', 'قانوني'), ('marketing', 'تسويق'), ('payment', 'الدفع'), ('other', 'أخرى')], default='website', max_length=20, verbose_name='الفئة')),
                ('placement', models.CharField(choices=[('footer', 'تذييل الموقع'), ('header', 'رأس الموقع'), ('sidebar', 'الشريط الجانبي'), ('landing', 'صفحة الهبوط'), ('mobile', 'تطبيق الجوال'), ('all', 'جميع الأماكن')], default='all', max_length=20, verbose_name='مكان العرض')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('icon', models.CharField(blank=True, max_length=64, verbose_name='أيقونة مخصصة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_featured', models.BooleanField(default=False, verbose_name='مميز')),
                ('open_in_new_tab', models.BooleanField(default=True, verbose_name='فتح في تبويب جديد')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('click_count', models.PositiveIntegerField(default=0, verbose_name='عدد النقرات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_external_links', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_links', to='platforms.platform', verbose_name='المنصة')),
            ],
            options={
                'verbose_name': 'رابط خارجي',
                'verbose_name_plural': 'الروابط الخارجية',
                'ordering': ['sort_order', '-is_featured', '-created_at'],
            },
        ),
    ]
