# Generated by Django 5.0.6 on 2026-06-13 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(blank=True, max_length=255, verbose_name='البريد')),
                ('user_name', models.CharField(blank=True, max_length=255, verbose_name='الاسم')),
                ('user_role', models.CharField(blank=True, max_length=30, verbose_name='الدور')),
                ('action', models.CharField(choices=[('create', 'إنشاء'), ('update', 'تحديث'), ('delete', 'حذف'), ('login', 'تسجيل دخول'), ('logout', 'تسجيل خروج'), ('view', 'عرض'), ('export', 'تصدير'), ('import', 'استيراد'), ('publish', 'نشر'), ('approve', 'موافقة'), ('reject', 'رفض'), ('test', 'اختبار'), ('system', 'نظام'), ('other', 'أخرى')], default='other', max_length=20)),
                ('category', models.CharField(choices=[('auth', 'المصادقة'), ('events', 'الفعاليات'), ('guests', 'الضيوف'), ('platforms', 'المنصات'), ('integrations', 'التكاملات'), ('static_pages', 'الصفحات الثابتة'), ('external_links', 'الروابط الخارجية'), ('public_media', 'الوسائط والهبوط'), ('announcements', 'الإعلانات'), ('faq', 'الأسئلة'), ('reports', 'التقارير'), ('staff', 'الطاقم'), ('messages', 'الرسائل'), ('monitoring', 'المراقبة'), ('system', 'النظام'), ('other', 'أخرى')], default='other', max_length=30)),
                ('status', models.CharField(choices=[('success', 'نجاح'), ('failure', 'فشل'), ('warning', 'تحذير')], default='success', max_length=20)),
                ('object_type', models.CharField(blank=True, max_length=120, verbose_name='نوع العنصر')),
                ('object_id', models.CharField(blank=True, max_length=64, verbose_name='معرّف العنصر')),
                ('object_repr', models.CharField(blank=True, max_length=500, verbose_name='العنصر')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='المتصفح')),
                ('request_path', models.CharField(blank=True, max_length=500, verbose_name='المسار')),
                ('request_method', models.CharField(blank=True, max_length=10, verbose_name='الطريقة')),
                ('platform_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='المنصة')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='التاريخ')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل نشاط',
                'verbose_name_plural': 'سجلات النشاط',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'category'], name='activity_lo_created_d965ee_idx'), models.Index(fields=['user', '-created_at'], name='activity_lo_user_id_04b3d2_idx'), models.Index(fields=['action', '-created_at'], name='activity_lo_action_182b05_idx')],
            },
        ),
    ]
