# Generated by Django 5.0.6 on 2026-06-04 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('capacity', models.PositiveIntegerField(default=8, verbose_name='السعة')),
                ('shape', models.CharField(choices=[('round', 'دائري'), ('rectangle', 'مستطيل'), ('square', 'مربع')], default='round', max_length=15, verbose_name='الشكل')),
                ('position_x', models.FloatField(default=0, verbose_name='الموقع X')),
                ('position_y', models.FloatField(default=0, verbose_name='الموقع Y')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='events.event', verbose_name='الفعالية')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tables', to='events.section', verbose_name='القسم')),
            ],
            options={
                'verbose_name': 'طاولة',
                'verbose_name_plural': 'الطاولات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TableSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.PositiveIntegerField(verbose_name='رقم المقعد')),
                ('guest', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seat', to='guests.guest', verbose_name='الضيف')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='tables.table', verbose_name='الطاولة')),
            ],
            options={
                'verbose_name': 'مقعد',
                'verbose_name_plural': 'المقاعد',
                'unique_together': {('table', 'seat_number')},
            },
        ),
    ]
