# Generated by Django 5.0.6 on 2026-06-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(default='مرحّاب', max_length=120, verbose_name='اسم المنصة')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='system/', verbose_name='شعار المنصة')),
                ('default_language', models.CharField(choices=[('ar_SA', 'العربية (المملكة العربية السعودية)'), ('en_GB', 'English (United Kingdom)')], default='ar_SA', max_length=10, verbose_name='اللغة الافتراضية')),
                ('timezone', models.CharField(choices=[('Asia/Riyadh', '(GMT+03:00) الرياض'), ('Asia/Dubai', '(GMT+04:00) دبي')], default='Asia/Riyadh', max_length=40, verbose_name='المنطقة الزمنية')),
                ('theme_primary', models.CharField(default='#5b2eff', max_length=7, verbose_name='اللون الأساسي')),
                ('notify_email', models.BooleanField(default=True, verbose_name='إشعارات البريد')),
                ('notify_sms', models.BooleanField(default=False, verbose_name='إشعارات SMS')),
                ('notify_whatsapp', models.BooleanField(default=True, verbose_name='إشعارات واتساب')),
                ('notify_push', models.BooleanField(default=True, verbose_name='إشعارات التطبيق')),
                ('notify_system_alerts', models.BooleanField(default=True, verbose_name='تنبيهات النظام')),
                ('qr_validity', models.CharField(choices=[('48h', '48 ساعة'), ('7d', 'أسبوع واحد'), ('open', 'مفتوح (بدون انتهاء)')], default='48h', max_length=10, verbose_name='مدة صلاحية QR')),
                ('rsvp_auto_enabled', models.BooleanField(default=True, verbose_name='تفعيل RSVP تلقائياً')),
                ('high_res_headers_only', models.BooleanField(default=False, verbose_name='صور ترويسة عالية الدقة فقط')),
                ('ticket_format', models.CharField(choices=[('digital', 'بطاقة رقمية (Standard)'), ('pdf', 'ملف PDF'), ('web', 'رابط ويب فقط')], default='digital', max_length=20, verbose_name='تنسيق التذاكر')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'إعدادات النظام',
                'verbose_name_plural': 'إعدادات النظام',
            },
        ),
    ]
