/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        surface: "#12121d",
        "primary-container": "#5b2eff",
        "inverse-surface": "#e3e0f1",
        "tertiary-fixed-dim": "#ffb59b",
        "on-error": "#690005",
        tertiary: "#ffb59b",
        "on-tertiary-fixed-variant": "#812800",
        "surface-bright": "#383845",
        "on-background": "#e3e0f1",
        "on-tertiary-fixed": "#380d00",
        "tertiary-container": "#aa3800",
        "on-tertiary-container": "#ffcfbf",
        "surface-dim": "#12121d",
        "secondary-container": "#47475d",
        "on-secondary-fixed-variant": "#45455b",
        "error-container": "#93000a",
        secondary: "#c6c4df",
        "on-surface-variant": "#c9c3da",
        "surface-container": "#1f1e2a",
        "inverse-on-surface": "#302f3b",
        "surface-container-low": "#1b1a26",
        "primary-fixed-dim": "#c8bfff",
        error: "#ffb4ab",
        "on-surface": "#e3e0f1",
        "on-primary-fixed-variant": "#4200da",
        primary: "#c8bfff",
        "on-tertiary": "#5b1a00",
        "inverse-primary": "#5a2dfe",
        "on-secondary-container": "#b8b6d0",
        "on-primary-fixed": "#190064",
        "tertiary-fixed": "#ffdbcf",
        "surface-container-lowest": "#0d0d18",
        background: "#12121d",
        outline: "#928ea3",
        "on-primary": "#2d009d",
        "secondary-fixed-dim": "#c6c4df",
        "outline-variant": "#474557",
        "surface-container-highest": "#343440",
        "on-primary-container": "#dcd4ff",
        "on-secondary": "#2f2e43",
        "secondary-fixed": "#e2e0fc",
        "surface-container-high": "#292935",
        "surface-variant": "#343440",
        "surface-tint": "#c8bfff",
        "primary-fixed": "#e5deff",
        "on-error-container": "#ffdad6",
        "on-secondary-fixed": "#1a1a2e",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans", "Noto Sans Arabic", "sans-serif"],
        body: ["Inter", "Noto Sans Arabic", "sans-serif"],
        label: ["Inter", "Noto Sans Arabic", "sans-serif"],
      },
    },
  },
  plugins: [],
};
