# Generated by Django 5.0.6 on 2026-06-04 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('email', 'بريد إلكتروني'), ('sms', 'رسالة نصية'), ('whatsapp', 'واتساب'), ('qr', 'رمز QR')], default='email', max_length=15, verbose_name='طريقة الإرسال')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('sent', 'تم الإرسال'), ('delivered', 'تم التسليم'), ('opened', 'تم الفتح'), ('failed', 'فشل')], default='pending', max_length=15, verbose_name='الحالة')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='الموضوع')),
                ('message', models.TextField(blank=True, verbose_name='الرسالة')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإرسال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='events.event', verbose_name='الفعالية')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='guests.guest', verbose_name='الضيف')),
            ],
            options={
                'verbose_name': 'دعوة',
                'verbose_name_plural': 'الدعوات',
                'ordering': ['-created_at'],
            },
        ),
    ]
