# Generated by Django 5.0.6 on 2026-06-16 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0007_platform_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='يُستخدم لإرسال دعوات الفعاليات عبر واتساب (صيغة E.164)', max_length=20, verbose_name='رقم واتساب الدعوات'),
        ),
    ]
