# Generated by Django 5.0.6 on 2026-07-05 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0009_usernotification_enhanced'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='usernotification',
            name='notif_user_read_idx',
        ),
        migrations.RemoveIndex(
            model_name='usernotification',
            name='notif_event_kind_idx',
        ),
    ]
