# Generated by Django 5.0.6 on 2026-06-13 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='المعرّف')),
                ('page_type', models.CharField(choices=[('about_us', 'من نحن'), ('privacy_policy', 'سياسة الخصوصية'), ('terms_of_use', 'شروط الاستخدام'), ('cookie_policy', 'سياسة ملفات تعريف الارتباط'), ('refund_policy', 'سياسة الاسترداد'), ('event_guidelines', 'إرشادات المناسبات'), ('guest_policy', 'سياسة الضيوف والحضور'), ('contact_info', 'تواصل معنا'), ('custom', 'صفحة مخصصة')], default='custom', max_length=30, verbose_name='نوع الصفحة')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('subtitle', models.CharField(blank=True, max_length=500, verbose_name='العنوان الفرعي')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('meta_title', models.CharField(blank=True, max_length=255, verbose_name='عنوان SEO')),
                ('meta_description', models.CharField(blank=True, max_length=500, verbose_name='وصف SEO')),
                ('icon', models.CharField(blank=True, default='article', max_length=64, verbose_name='أيقونة')),
                ('is_published', models.BooleanField(default=False, verbose_name='منشورة')),
                ('show_in_footer', models.BooleanField(default=True, verbose_name='عرض في التذييل')),
                ('show_in_header', models.BooleanField(default=False, verbose_name='عرض في الرأس')),
                ('show_on_landing', models.BooleanField(default=True, verbose_name='عرض في صفحة الهبوط')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ النشر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_static_pages', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
            ],
            options={
                'verbose_name': 'صفحة ثابتة',
                'verbose_name_plural': 'الصفحات الثابتة',
                'ordering': ['sort_order', '-updated_at'],
            },
        ),
    ]
