# Generated by Django 5.0.6 on 2026-06-04 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('coordinator', 'منسق'), ('usher', 'مرشد'), ('security', 'أمن'), ('catering', 'تموين'), ('technical', 'تقني'), ('other', 'أخرى')], default='other', max_length=20, verbose_name='الدور')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التعيين')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='events.event', verbose_name='الفعالية')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'طاقم العمل',
                'verbose_name_plural': 'طاقم العمل',
                'unique_together': {('event', 'user')},
            },
        ),
    ]
