# Generated by Django 5.0.6 on 2026-07-05 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='role',
            field=models.CharField(choices=[('coordinator', 'منسق'), ('entry_manager', 'مدير دخول'), ('usher', 'مرشد'), ('security', 'أمن'), ('catering', 'تموين'), ('technical', 'تقني'), ('other', 'أخرى')], default='other', max_length=20, verbose_name='الدور'),
        ),
    ]
