# Generated by Django 5.0.6 on 2026-06-04 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('time', models.TimeField(verbose_name='الوقت')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='وقت الانتهاء')),
                ('venue', models.CharField(blank=True, max_length=255, verbose_name='المكان')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('active', 'نشط'), ('completed', 'مكتمل'), ('cancelled', 'ملغي')], default='draft', max_length=15, verbose_name='الحالة')),
                ('max_guests', models.PositiveIntegerField(default=0, verbose_name='الحد الأقصى للضيوف')),
                ('cover_image', models.ImageField(blank=True, upload_to='events/', verbose_name='صورة الغلاف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('managers', models.ManyToManyField(blank=True, related_name='managed_events', to=settings.AUTH_USER_MODEL, verbose_name='المدراء')),
            ],
            options={
                'verbose_name': 'فعالية',
                'verbose_name_plural': 'الفعاليات',
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('color', models.CharField(default='#5b2eff', max_length=7, verbose_name='اللون')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='events.event', verbose_name='الفعالية')),
            ],
            options={
                'verbose_name': 'مجموعة',
                'verbose_name_plural': 'المجموعات',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('start_time', models.DateTimeField(verbose_name='وقت البداية')),
                ('end_time', models.DateTimeField(verbose_name='وقت النهاية')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='الموقع')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='events.event', verbose_name='الفعالية')),
            ],
            options={
                'verbose_name': 'جدول',
                'verbose_name_plural': 'الجداول',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('color', models.CharField(default='#5b2eff', max_length=7, verbose_name='اللون')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='events.event', verbose_name='الفعالية')),
            ],
            options={
                'verbose_name': 'قسم',
                'verbose_name_plural': 'الأقسام',
                'ordering': ['order'],
            },
        ),
    ]
