# Generated by Django 5.0.6 on 2026-06-16 06:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_geo_fields'),
        ('platforms', '0008_add_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['platform', 'status'], name='events_even_platfor_879f60_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['platform', '-created_at'], name='events_even_platfor_81b422_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status', 'date'], name='events_even_status_d859e9_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['-created_at'], name='events_even_created_7af6de_idx'),
        ),
    ]
