# Generated by Django 5.0.6 on 2026-06-27 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_event_invitation_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='auto_reminder_enabled',
            field=models.BooleanField(default=False, help_text='يتطلّب مزوّداً رسمياً نشطاً (Twilio/Cloud) ليُرسل تلقائياً.', verbose_name='تفعيل التذكير التلقائي قبل الحفل'),
        ),
        migrations.AddField(
            model_name='event',
            name='auto_reminder_hours_before',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='عدد الساعات قبل الحفل لإرسال التذكير'),
        ),
        migrations.AddField(
            model_name='event',
            name='auto_reminder_sent_at',
            field=models.DateTimeField(blank=True, help_text='يُضبط تلقائياً عند الإرسال لمنع التكرار.', null=True, verbose_name='وقت إرسال التذكير التلقائي'),
        ),
    ]
