# Generated by Django 5.0.6 on 2026-06-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandingSiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='منصة إدارة المناسبات والفعاليات', max_length=255, verbose_name='عنوان الهبوط')),
                ('hero_subtitle', models.CharField(default='خطط لحفلاتك ومناسباتك بسهولة — دعوات، ضيوف، RSVP، وتقارير شاملة', max_length=500, verbose_name='العنوان الفرعي')),
                ('hero_description', models.TextField(blank=True, default='مرحّاب منصة سعودية متخصصة في إدارة المناسبات والفعاليات للأفراد والمؤسسات.', verbose_name='وصف الهبوط')),
                ('hero_cta_primary', models.CharField(default='ابدأ الآن', max_length=80, verbose_name='زر أساسي')),
                ('hero_cta_primary_url', models.CharField(default='/login', max_length=255, verbose_name='رابط الزر الأساسي')),
                ('hero_cta_secondary', models.CharField(default='تعرف علينا', max_length=80, verbose_name='زر ثانوي')),
                ('hero_cta_secondary_url', models.CharField(default='#about', max_length=255, verbose_name='رابط الزر الثانوي')),
                ('stats', models.JSONField(blank=True, default=list, help_text='قائمة {label, value, icon}', verbose_name='أرقام وإحصائيات')),
                ('features', models.JSONField(blank=True, default=list, help_text='قائمة {icon, title, description}', verbose_name='المميزات')),
                ('testimonials', models.JSONField(blank=True, default=list, verbose_name='شهادات العملاء')),
                ('partners_title', models.CharField(blank=True, default='شركاء النجاح', max_length=255, verbose_name='عنوان الشركاء')),
                ('gallery_title', models.CharField(blank=True, default='من معرض المناسبات', max_length=255, verbose_name='عنوان المعرض')),
                ('video_section_title', models.CharField(blank=True, default='شاهد مرحّاب', max_length=255, verbose_name='عنوان قسم الفيديو')),
                ('contact_email', models.EmailField(blank=True, default='support@merhab.sa', max_length=254, verbose_name='بريد التواصل')),
                ('contact_phone', models.CharField(blank=True, max_length=30, verbose_name='هاتف التواصل')),
                ('meta_title', models.CharField(blank=True, default='مرحّاب | إدارة المناسبات', max_length=255, verbose_name='SEO عنوان')),
                ('meta_description', models.CharField(blank=True, max_length=500, verbose_name='SEO وصف')),
                ('is_published', models.BooleanField(default=True, verbose_name='صفحة الهبوط منشورة')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'إعدادات صفحة الهبوط',
                'verbose_name_plural': 'إعدادات صفحة الهبوط',
            },
        ),
        migrations.CreateModel(
            name='PublicMediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='نص بديل')),
                ('media_type', models.CharField(choices=[('image', 'صورة'), ('video_url', 'رابط فيديو (YouTube/Vimeo)'), ('video_file', 'ملف فيديو')], default='image', max_length=20, verbose_name='نوع الوسائط')),
                ('section', models.CharField(choices=[('hero', 'الهبوط الرئيسي'), ('gallery', 'معرض الصور'), ('video', 'قسم الفيديو'), ('banner', 'بانر إعلاني'), ('features', 'صور المميزات')], default='gallery', max_length=20, verbose_name='القسم')),
                ('file', models.FileField(blank=True, null=True, upload_to='public_media/', verbose_name='ملف')),
                ('video_url', models.URLField(blank=True, max_length=500, verbose_name='رابط الفيديو')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='public_media/thumbs/', verbose_name='صورة مصغرة')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_featured', models.BooleanField(default=False, verbose_name='مميز')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'وسيط عام',
                'verbose_name_plural': 'الوسائط العامة',
                'ordering': ['section', 'sort_order', '-is_featured', '-created_at'],
            },
        ),
    ]
