# Generated by Django 5.0.6 on 2026-06-13 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_media', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='الاسم')),
                ('role', models.CharField(blank=True, max_length=120, verbose_name='الصفة / المؤسسة')),
                ('text', models.TextField(verbose_name='الرأي')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد')),
                ('status', models.CharField(choices=[('pending', 'بانتظار المراجعة'), ('approved', 'موافق عليه'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='الحالة')),
                ('show_on_landing', models.BooleanField(default=False, verbose_name='عرض في صفحة الهبوط')),
                ('source', models.CharField(choices=[('visitor', 'زائر'), ('admin', 'إدارة')], default='visitor', max_length=20, verbose_name='المصدر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_testimonials', to=settings.AUTH_USER_MODEL, verbose_name='راجع بواسطة')),
            ],
            options={
                'verbose_name': 'رأي عميل',
                'verbose_name_plural': 'آراء العملاء',
                'ordering': ['-created_at'],
            },
        ),
    ]
