# Generated by Django 5.0.6 on 2026-06-04 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='الاسم الكامل')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('status', models.CharField(choices=[('invited', 'مدعو'), ('confirmed', 'مؤكد'), ('attended', 'حضر'), ('declined', 'اعتذر'), ('cancelled', 'ملغي')], default='invited', max_length=15, verbose_name='الحالة')),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes/', verbose_name='رمز QR')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('dietary_requirements', models.TextField(blank=True, verbose_name='متطلبات غذائية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='events.event', verbose_name='الفعالية')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guests', to='events.group', verbose_name='المجموعة')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guests', to='events.section', verbose_name='القسم')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_profiles', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'ضيف',
                'verbose_name_plural': 'الضيوف',
                'ordering': ['full_name'],
                'unique_together': {('event', 'email')},
            },
        ),
    ]
