# Generated by Django 5.0.6 on 2026-06-16 06:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_add_performance_indexes'),
        ('guests', '0002_guestqrscanlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='guest',
            index=models.Index(fields=['event', 'status'], name='guests_gues_event_i_80021b_idx'),
        ),
        migrations.AddIndex(
            model_name='guest',
            index=models.Index(fields=['event', 'created_at'], name='guests_gues_event_i_6f502e_idx'),
        ),
        migrations.AddIndex(
            model_name='guest',
            index=models.Index(fields=['status'], name='guests_gues_status_13125c_idx'),
        ),
    ]
