# Generated by Django 5.0.6 on 2026-06-19 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0004_guest_public_token_seated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='status',
            field=models.CharField(choices=[('invited', 'مدعو'), ('confirmed', 'مؤكد الحضور'), ('attended', 'حضر'), ('seated', 'جلس'), ('declined', 'معتذر'), ('cancelled', 'ملغي')], default='invited', max_length=15, verbose_name='الحالة'),
        ),
    ]
