# Generated by Django 5.0.6 on 2026-06-30 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_account_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='recovery_email_enabled',
            field=models.BooleanField(default=True, verbose_name='تفعيل استعادة كلمة المرور عبر البريد'),
        ),
        migrations.CreateModel(
            name='PasswordResetCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=128, verbose_name='تجزئة الرمز')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('expires_at', models.DateTimeField(verbose_name='ينتهي في')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='محاولات خاطئة')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاستخدام')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_codes', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'رمز استعادة كلمة المرور',
                'verbose_name_plural': 'رموز استعادة كلمة المرور',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='accounts_pa_user_id_f243e1_idx')],
            },
        ),
    ]
