# Generated by Django 5.0.6 on 2026-06-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('section', models.CharField(choices=[('banner', 'إعلان / بانر (سلايدر)'), ('video', 'فيديو إعلاني')], default='banner', max_length=20, verbose_name='القسم')),
                ('media_type', models.CharField(choices=[('image', 'صورة'), ('video_url', 'رابط فيديو'), ('video_file', 'ملف فيديو')], default='image', max_length=20, verbose_name='نوع الوسائط')),
                ('image', models.ImageField(blank=True, null=True, upload_to='announcements/images/', verbose_name='صورة')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='announcements/videos/', verbose_name='ملف فيديو')),
                ('video_url', models.URLField(blank=True, max_length=500, verbose_name='رابط الفيديو')),
                ('link_url', models.URLField(blank=True, max_length=500, verbose_name='رابط عند النقر')),
                ('display_duration', models.PositiveIntegerField(default=5, help_text='مدة عرض الشريحة أو الفيديو في السلايدر', verbose_name='مدة الظهور (ثانية)')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('show_on_landing', models.BooleanField(default=True, verbose_name='عرض في صفحة الهبوط')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='يبدأ من')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='ينتهي في')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'إعلان',
                'verbose_name_plural': 'الإعلانات والبانرات',
                'ordering': ['section', 'sort_order', '-created_at'],
            },
        ),
    ]
