# Generated by Django 5.0.6 on 2026-06-13 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('whatsapp_cloud', 'WhatsApp Business API'), ('whatsapp_twilio', 'WhatsApp (Twilio)'), ('email_smtp', 'البريد الإلكتروني (SMTP)'), ('email_sendgrid', 'SendGrid'), ('email_mailgun', 'Mailgun'), ('sms_twilio', 'Twilio SMS'), ('sms_unifonic', 'Unifonic'), ('payment_stripe', 'Stripe'), ('payment_moyasar', 'Moyasar'), ('maps_google', 'Google Maps'), ('storage_s3', 'AWS S3'), ('firebase', 'Firebase'), ('push_onesignal', 'OneSignal'), ('custom', 'تكامل مخصص')], max_length=40, verbose_name='المزود')),
                ('category', models.CharField(choices=[('messaging', 'الرسائل والواتساب'), ('email', 'البريد الإلكتروني'), ('sms', 'الرسائل النصية'), ('payment', 'الدفع'), ('maps', 'الخرائط'), ('storage', 'التخزين'), ('push', 'الإشعارات الفورية'), ('other', 'أخرى')], max_length=20, verbose_name='الفئة')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('environment', models.CharField(choices=[('sandbox', 'تجريبي'), ('production', 'إنتاج')], default='production', max_length=20, verbose_name='البيئة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_primary', models.BooleanField(default=False, verbose_name='أساسي للفئة')),
                ('api_key', models.CharField(blank=True, max_length=512, verbose_name='مفتاح API')),
                ('api_secret', models.CharField(blank=True, max_length=512, verbose_name='سر API')),
                ('access_token', models.CharField(blank=True, max_length=512, verbose_name='رمز الوصول')),
                ('refresh_token', models.CharField(blank=True, max_length=512, verbose_name='رمز التحديث')),
                ('phone_number_id', models.CharField(blank=True, max_length=100, verbose_name='معرف رقم الهاتف')),
                ('business_account_id', models.CharField(blank=True, max_length=100, verbose_name='معرف الحساب التجاري')),
                ('from_email', models.EmailField(blank=True, max_length=254, verbose_name='البريد المرسل')),
                ('from_name', models.CharField(blank=True, max_length=255, verbose_name='اسم المرسل')),
                ('smtp_host', models.CharField(blank=True, max_length=255, verbose_name='خادم SMTP')),
                ('smtp_port', models.PositiveIntegerField(blank=True, null=True, verbose_name='منفذ SMTP')),
                ('smtp_use_tls', models.BooleanField(default=True, verbose_name='TLS')),
                ('webhook_url', models.URLField(blank=True, verbose_name='رابط Webhook')),
                ('webhook_secret', models.CharField(blank=True, max_length=255, verbose_name='سر Webhook')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='إعدادات إضافية')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('last_tested_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر اختبار')),
                ('last_test_status', models.CharField(choices=[('never', 'لم يُختبر'), ('success', 'ناجح'), ('failed', 'فشل')], default='never', max_length=20, verbose_name='نتيجة الاختبار')),
                ('last_test_error', models.TextField(blank=True, verbose_name='خطأ الاختبار')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_integrations', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
            ],
            options={
                'verbose_name': 'تكامل خارجي',
                'verbose_name_plural': 'التكاملات الخارجية',
                'ordering': ['-is_primary', '-is_active', '-updated_at'],
            },
        ),
    ]
