# Generated by Django 5.0.6 on 2026-06-04 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('guest_list', 'قائمة الضيوف'), ('attendance', 'الحضور'), ('seating', 'توزيع المقاعد'), ('invitations', 'الدعوات'), ('summary', 'ملخص')], max_length=20, verbose_name='نوع التقرير')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('data', models.JSONField(default=dict, verbose_name='البيانات')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التوليد')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='events.event', verbose_name='الفعالية')),
            ],
            options={
                'verbose_name': 'تقرير',
                'verbose_name_plural': 'التقارير',
                'ordering': ['-generated_at'],
            },
        ),
    ]
