# Generated by Django 5.0.6 on 2026-06-13 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='السؤال')),
                ('answer', models.TextField(blank=True, verbose_name='الرد')),
                ('asker_name', models.CharField(blank=True, max_length=120, verbose_name='اسم السائل')),
                ('asker_email', models.EmailField(blank=True, max_length=254, verbose_name='بريد السائل')),
                ('status', models.CharField(choices=[('pending', 'بانتظار الرد'), ('answered', 'تم الرد'), ('closed', 'مغلق')], default='pending', max_length=20, verbose_name='الحالة')),
                ('is_published', models.BooleanField(default=False, help_text='يُعرض فقط عند وجود رد', verbose_name='عرض في صفحة الهبوط')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الرد')),
                ('answered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faq_replies', to=settings.AUTH_USER_MODEL, verbose_name='رد بواسطة')),
            ],
            options={
                'verbose_name': 'سؤال / استفسار',
                'verbose_name_plural': 'الأسئلة والاستفسارات',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
